version: "3"
services:
  mosquitto:
    image: toke/mosquitto
    container_name: mosquitto
    entrypoint: mosquitto -v
    ports:
    - 1883:1883
    volumes:
    - ./etc/mosquitto:/etc/mosquitto:ro
    - ./var/log/mosquitto:/var/log/mosquitto:rw
    network_mode: host
  feedbackbtn-backend:
    build: .
    container_name: feedbackbtn-backend
    network_mode: host
    depends_on:
    - mosquitto
    ports:
    - "8000:8000"
    volumes:
    - ./server/static:/static
    environment:
    - STATIC=/static
